import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:daily_life/services/tts_service.dart';
import 'package:daily_life/services/tts_io.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('TtsService', () {
    late Directory tempDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('tts_service_test_');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('cache miss calls client, writes cache, and plays', () async {
      final client = _FakeTtsClient({
        'สวัสดี': Uint8List.fromList([1, 2, 3]),
      });
      final cache = LocalTtsAudioCache(directoryProvider: () async => tempDir);
      final player = _FakeTtsAudioPlayer();
      final service = TtsService(client: client, cache: cache, player: player);

      await service.speak('สวัสดี');

      expect(client.requests, ['สวัสดี']);
      expect(player.playedBytes, hasLength(1));
      expect(player.playedBytes.single, [1, 2, 3]);
    });

    test('cache hit does not call client', () async {
      final cache = LocalTtsAudioCache(directoryProvider: () async => tempDir);
      await cache.put(ttsCacheKey('แมว'), Uint8List.fromList([7, 8]));
      final client = _FakeTtsClient({});
      final player = _FakeTtsAudioPlayer();
      final service = TtsService(client: client, cache: cache, player: player);

      await service.speak('แมว');

      expect(client.requests, isEmpty);
      expect(player.playedBytes, hasLength(1));
      expect(player.playedBytes.single, [7, 8]);
    });

    test(
      'repeated speak cancels prior playback and only latest plays',
      () async {
        final client = _QueuedTtsClient();
        final cache = LocalTtsAudioCache(
          directoryProvider: () async => tempDir,
        );
        final player = _FakeTtsAudioPlayer();
        final service = TtsService(
          client: client,
          cache: cache,
          player: player,
        );

        final first = service.speak('หนึ่ง');
        await client.waitForRequest('หนึ่ง');
        final second = service.speak('สอง');
        await client.waitForRequest('สอง');

        client.complete('สอง', Uint8List.fromList([2]));
        await second;
        client.complete('หนึ่ง', Uint8List.fromList([1]));
        await first;

        expect(player.stopCount, greaterThanOrEqualTo(2));
        expect(player.playedBytes, hasLength(1));
        expect(player.playedBytes.single, [2]);
      },
    );

    test(
      'cancel prevents stale in-flight synth results from playing',
      () async {
        final client = _QueuedTtsClient();
        final cache = LocalTtsAudioCache(
          directoryProvider: () async => tempDir,
        );
        final player = _FakeTtsAudioPlayer();
        final service = TtsService(
          client: client,
          cache: cache,
          player: player,
        );

        final speak = service.speak('หยุด');
        await client.waitForRequest('หยุด');
        await service.cancel();
        client.complete('หยุด', Uint8List.fromList([1]));
        await speak;

        expect(player.playedBytes, isEmpty);
      },
    );

    test('synth returns generated bytes and uses cache', () async {
      final client = _FakeTtsClient({
        'ปลา': Uint8List.fromList([4, 5]),
      });
      final cache = LocalTtsAudioCache(directoryProvider: () async => tempDir);
      final player = _FakeTtsAudioPlayer();
      final service = TtsService(client: client, cache: cache, player: player);

      final first = await service.synth('ปลา');
      final second = await service.synth('ปลา');

      expect(first, [4, 5]);
      expect(second, [4, 5]);
      expect(client.requests, ['ปลา']);
    });
  });
}

class _FakeTtsClient implements TtsClient {
  _FakeTtsClient(this.responses);

  final Map<String, Uint8List> responses;
  final requests = <String>[];

  @override
  Future<Uint8List> synthesize(String text) async {
    requests.add(text);
    return responses[text] ?? Uint8List(0);
  }
}

class _QueuedTtsClient implements TtsClient {
  final requests = <String>[];
  final _completers = <String, Completer<Uint8List>>{};
  final _requestWaiters = <String, Completer<void>>{};

  @override
  Future<Uint8List> synthesize(String text) {
    requests.add(text);
    final completer = Completer<Uint8List>();
    _completers[text] = completer;
    _requestWaiters.remove(text)?.complete();
    return completer.future;
  }

  Future<void> waitForRequest(String text) {
    if (requests.contains(text)) return Future<void>.value();
    return (_requestWaiters[text] ??= Completer<void>()).future;
  }

  void complete(String text, Uint8List bytes) {
    _completers.remove(text)!.complete(bytes);
  }
}

class _FakeTtsAudioPlayer implements TtsAudioPlayer {
  final playedBytes = <Uint8List>[];
  var stopCount = 0;
  var disposed = false;

  @override
  Future<void> playBytes(Uint8List bytes) async {
    playedBytes.add(bytes);
  }

  @override
  Future<void> stop() async {
    stopCount++;
  }

  @override
  Future<void> dispose() async {
    disposed = true;
  }
}
