// Generated by `flutterfire configure` — Firebase project: kaokeng-app (android + web).
// Regenerate with `flutterfire configure` if apps/platforms change.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For testing on web, use web config (same Firebase project).
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'FirebaseOptions for ${defaultTargetPlatform.name} are not configured yet — '
          'Android is the MVP target (spec 01 §Platform Targets).',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_WP6GCnn4N_lEFA98iKOLHOTvoZyexI',
    appId: '1:305078404807:android:97d296f474c4699700e0e2',
    messagingSenderId: '305078404807',
    projectId: 'kaokeng-app',
    storageBucket: 'kaokeng-app.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOYuMIhTxlVd-5XhDGxV88zdVuBUgk0I',
    appId: '1:305078404807:web:f283a2ee0da94dec00e0e2',
    messagingSenderId: '305078404807',
    projectId: 'kaokeng-app',
    authDomain: 'kaokeng-app.firebaseapp.com',
    storageBucket: 'kaokeng-app.firebasestorage.app',
    measurementId: 'G-7SKLV9QLMC',
  );
}
